### ISSUE TITLE
Does not work on NVIDIA + Wayland

### ISSUE THREAD

**Issue by IceDBorn** [clague/ds3os-loader-rs#4]
Running the executable from the terminal presents this error
`Error: a suitable graphics adapter or device could not be found`

**Comment by clague** [comment]
Try to force it run in XWayland
for example: `WAYLAND_DISPLAY="" ./ds3os-loader`

You can also try this which use Vulkan instead of OpenGL. The problem may be using NVIDIA as OpenGL Renderer in Wayland. 

[ds3os-loader.zip](https://github.com/clague/ds3os-loader-rs/files/9146802/ds3os-loader.zip)(Don't run in XWayland)

**Comment by IceDBorn** [comment]
The one you uploaded works just fine on Wayland
