### ISSUE TITLE
Unable to run loader

### ISSUE THREAD

**Issue by EndEmpire** [clague/ds3os-loader-rs#5]
Hello! I'll be blunt, I'm still a noob in regards to Linux so I hope you can forgive me if the answer here is obvious.

I was able to build the [ds3os-loader] from source after installing all the packages listed in the first issue and rusting up my machine, but it still pops up as an "Unknown File Type" when I try to run it.
Any help would be appreciated! Thank you for your time!

I'm running: Linux Mint 20.3 x86_64

**Comment by cndofx** [comment]
You might need to explicitly execute it rather than open it. Does it work if you run it through the terminal? Go into the directory its in and run `./ds3os-loader` or whatever the binary was called. If you get an error about permissions, you might need to do something like `chmod +x ds3os-loader` first, but I don't think that should be necessary.

**Comment by clague** [comment]
you can run `cargo run --release` to directly run it from cargo

Or as [cndofx](https://github.com/cndofx) said, build up the binary, give the execute permission by `chmod +x ds3os-loader`, then run `./ds3os-loader` in terminal.

**Comment by EndEmpire** [comment]
Sorry! I just realized I left this open! Your advice worked great @cndofx and thank you for the further info @clague! Take care!
